import { Memory, User } from './types';

export const featuredMemories: Memory[] = [
  {
    id: '1',
    title: 'The Battle of Hogwarts',
    description: 'Experience the final battle between Harry Potter and Lord Voldemort firsthand. Feel the tension and magic in the air as the fate of the wizarding world hangs in the balance.',
    owner: 'Minerva McGonagall',
    price: 1299,
    category: 'Historical Events',
    rarity: 'Legendary',
    age: '25 years',
    thumbnail: 'https://images.pexels.com/photos/4314574/pexels-photo-4314574.jpeg',
    previewUrl: '/memories/battle-of-hogwarts',
    createdAt: '2023-05-02',
    isFeatured: true,
  },
  {
    id: '2',
    title: 'Quidditch World Cup Final',
    description: 'Soar through the air with the world\'s best Quidditch players. Experience the thrill of the World Cup final match from a player\'s perspective.',
    owner: 'Viktor Krum',
    price: 899,
    category: 'Quidditch Matches',
    rarity: 'Rare',
    age: '30 years',
    thumbnail: 'https://images.pexels.com/photos/1486064/pexels-photo-1486064.jpeg',
    previewUrl: '/memories/quidditch-final',
    createdAt: '2023-06-15',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Encounter with a Hungarian Horntail',
    description: 'Face one of the most fearsome dragons in the wizarding world. Experience the adrenaline and fear as you navigate around this magnificent creature.',
    owner: 'Charlie Weasley',
    price: 1099,
    category: 'Magical Creatures',
    rarity: 'Rare',
    age: '15 years',
    thumbnail: 'https://images.pexels.com/photos/4308189/pexels-photo-4308189.jpeg',
    previewUrl: '/memories/horntail-encounter',
    createdAt: '2023-07-23',
    isFeatured: true,
  },
  {
    id: '4',
    title: 'First Discovery of Felix Felicis',
    description: 'Witness the moment when the Luck Potion was first successfully brewed. Experience the elation and surprise of this magical breakthrough.',
    owner: 'Horace Slughorn',
    price: 1599,
    category: 'Potions Discovery',
    rarity: 'Mythic',
    age: '142 years',
    thumbnail: 'https://images.pexels.com/photos/3987158/pexels-photo-3987158.jpeg',
    previewUrl: '/memories/felix-felicis',
    createdAt: '2023-08-10',
    isFeatured: true,
  },
];

export const allMemories: Memory[] = [
  ...featuredMemories,
  {
    id: '5',
    title: 'Hidden Chambers of Gringotts',
    description: 'Delve deep into the most secure vaults of Gringotts Wizarding Bank. See the incredible security measures and treasures hidden within.',
    owner: 'Bill Weasley',
    price: 1499,
    category: 'Magical Places',
    rarity: 'Legendary',
    age: '12 years',
    thumbnail: 'https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg',
    previewUrl: '/memories/gringotts-chambers',
    createdAt: '2023-09-05',
    isFeatured: false,
  },
  {
    id: '6',
    title: 'Duel at the Department of Mysteries',
    description: 'Witness the legendary duel between Albus Dumbledore and Lord Voldemort at the Ministry of Magic.',
    owner: 'Kingsley Shacklebolt',
    price: 1999,
    category: 'Wizarding Duels',
    rarity: 'Mythic',
    age: '28 years',
    thumbnail: 'https://images.pexels.com/photos/7919/pexels-photo.jpg',
    previewUrl: '/memories/ministry-duel',
    createdAt: '2023-10-12',
    isFeatured: false,
  },
  {
    id: '7',
    title: 'Founding of Hogwarts',
    description: 'Travel back in time to witness the four founders establish Hogwarts School of Witchcraft and Wizardry.',
    owner: 'Bathilda Bagshot',
    price: 2499,
    category: 'Historical Events',
    rarity: 'Mythic',
    age: '1000+ years',
    thumbnail: 'https://images.pexels.com/photos/11852931/pexels-photo-11852931.jpeg',
    previewUrl: '/memories/hogwarts-founding',
    createdAt: '2023-11-01',
    isFeatured: false,
  },
  {
    id: '8',
    title: 'First Flight on a Hippogriff',
    description: 'Experience the thrill and wonder of flying on a magnificent Hippogriff for the first time.',
    owner: 'Rubeus Hagrid',
    price: 799,
    category: 'Magical Creatures',
    rarity: 'Uncommon',
    age: '8 years',
    thumbnail: 'https://images.pexels.com/photos/10621875/pexels-photo-10621875.jpeg',
    previewUrl: '/memories/hippogriff-flight',
    createdAt: '2023-12-15',
    isFeatured: false,
  },
];

export const dummyUser: User = {
  id: '1',
  name: 'Harry Potter',
  avatar: 'https://images.pexels.com/photos/2755165/pexels-photo-2755165.jpeg?auto=compress&cs=tinysrgb&w=150',
  memories: [],
  purchasedMemories: [allMemories[2], allMemories[5]],
};

export const categories = [
  'Magical Creatures',
  'Wizarding Duels',
  'Quidditch Matches',
  'Potions Discovery',
  'Magical Places',
  'Historical Events',
  'Personal',
];

export const rarities = [
  'Common',
  'Uncommon',
  'Rare',
  'Legendary',
  'Mythic',
];